KB_ARTICLES = {
    "KB-01": {
        "title": "Password Reset",
        "text": (
            "Employees can reset their own password via the self-service portal "
            "at any time. If locked out after 5 failed attempts, contact IT to "
            "unlock the account manually. No approval required."
        ),
        "keywords": ["password", "locked out", "login", "log in", "reset", "account locked"],
    },
    "KB-02": {
        "title": "VPN Access",
        "text": (
            "VPN access is granted automatically to all full-time employees. "
            "Contractors require manager approval submitted via the access "
            "request form. VPN credentials expire every 90 days and must be "
            "renewed by the employee."
        ),
        "keywords": ["vpn", "credentials expired", "remote access"],
    },
    "KB-03": {
        "title": "Laptop Replacement",
        "text": (
            "Laptops are eligible for replacement after 3 years of service, or "
            "earlier in case of verified hardware failure. Requests must be "
            "raised at least 2 weeks in advance of intended replacement."
        ),
        "keywords": ["laptop", "won't turn on", "wont turn on", "dead", "screen flickering",
                     "hardware failure", "replacement"],
    },
    "KB-04": {
        "title": "Software Installation Requests",
        "text": (
            "Standard software (listed in the approved catalog) can be "
            "self-installed. Non-catalog software requires IT Security review, "
            "which takes 3-5 business days."
        ),
        "keywords": ["install", "software", "extension", "application", "tool access"],
    },
    "KB-05": {
        "title": "Printer Troubleshooting",
        "text": (
            "For printer issues, first check the printer queue and restart the "
            "print spooler. If the issue persists after restart, log a ticket "
            "with the printer's asset tag."
        ),
        "keywords": ["printer", "paper jam", "print"],
    },
    "KB-06": {
        "title": "Email Mailbox Quota",
        "text": (
            "Default mailbox quota is 25GB. Employees nearing quota should "
            "archive old mail. Quota increases beyond 25GB require manager "
            "approval and are capped at 50GB."
        ),
        "keywords": ["mailbox", "quota", "email full", "can't send emails", "cant send emails"],
    },
    "KB-07": {
        "title": "Guest Wi-Fi Access",
        "text": (
            "Guest Wi-Fi credentials are valid for 24 hours and can be "
            "generated by any employee from the front-desk kiosk. No IT "
            "ticket required."
        ),
        "keywords": ["guest wifi", "guest wi-fi", "visitor wifi", "wifi access"],
    },
    "KB-08": {
        "title": "Expense Software Access",
        "text": (
            "Access to the expense management tool is granted by Finance, not "
            "IT. IT can only assist with login/technical issues once an "
            "account already exists."
        ),
        "keywords": ["expense", "expense tool", "invalid credentials"],
    },
    "KB-09": {
        "title": "Security Incident Reporting",
        "text": (
            "Any suspected phishing email, malware, or unauthorized access "
            "attempt must be reported to security@veridian-corp.example "
            "immediately and should not be forwarded to other employees."
        ),
        "keywords": ["phishing", "malware", "suspicious email", "unauthorized access", "security"],
    },
    "KB-10": {
        "title": "Work-From-Home Equipment",
        "text": (
            "Employees working remotely more than 3 days/week are eligible "
            "for a one-time home office equipment allowance (chair, monitor). "
            "Requires manager sign-off and Finance processing — IT only "
            "handles the equipment shipping request once approved."
        ),
        "keywords": ["work from home", "wfh", "home office", "monitor", "chair", "remote"],
    },
    "ASSET-POLICY": {
        "title": "Asset Management Policy (Extract, Finance & Assets, Q2 2026)",
        "text": (
            "All company-issued hardware, including laptops and monitors, "
            "follows a standard 4-year refresh cycle from date of issue. "
            "Early replacement outside this cycle requires Finance sign-off "
            "in addition to IT approval."
        ),
        "keywords": ["refresh cycle", "asset", "finance sign-off", "early replacement"],
    },
    "ADMIN-ACCESS": {
        "title": "No policy exists for elevated/admin access requests",
        "text": (
            "There is no KB article or policy in this data pack covering "
            "admin/elevated access to internal servers (e.g. finance "
            "reporting server). Precedent: TK-1050 was rejected for lack of "
            "business justification. Must not be resolved by IT alone."
        ),
        "keywords": ["admin access", "elevated access", "finance reporting server", "root access"],
    },
}

CATEGORY_TO_KB = {
    "password_reset": ["KB-01"],
    "vpn_access": ["KB-02"],
    "laptop_hardware": ["KB-03", "ASSET-POLICY"],
    "software_install": ["KB-04"],
    "printer_issue": ["KB-05"],
    "mailbox_quota": ["KB-06"],
    "guest_wifi": ["KB-07"],
    "expense_tool_access": ["KB-08"],
    "security_incident": ["KB-09"],
    "wfh_equipment": ["KB-10"],
    "admin_access_request": ["ADMIN-ACCESS"],
    "unclear": [],
}